# Generated by Django 4.0.2 on 2022-03-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
