# Generated by Django 4.0.2 on 2022-03-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
