# Generated by Django 4.0.2 on 2022-03-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
